sensor_setup: ['forward_rgb']
habitat_data:
  metadata_path: '/home/zhanxin/foundation_obj_nav/data/objectnav/gibson/v1.1/val/val.json.gz'
  content_scenes: ["Collierville_episodes", "Corozal_episodes"]
  scenes_dir: "/home/zhanxin/foundation_obj_nav/data/scene_datasets"